106 user prense resolverspec
kbarbry/ft_transcendence pull request #110
Opened 2023-10-20 12:04 UTC by Chicanoss

Done for NanoIdtest

2023-10-25 17:32 UTC, kbarbry requested changes

2023-10-25 17:32 UTC, kbarbry commented on backend/src/user-presence/user-presence.resolver.spec.ts
> +    //////////////////
ciao

2023-10-25 17:32 UTC, kbarbry commented on backend/src/user-presence/user-presence.resolver.spec.ts
>  //check with invalid user
ciao

2023-10-25 17:32 UTC, kbarbry commented on backend/src/user-presence/user-presence.resolver.spec.ts
> +
test ValidationPipe

2023-10-25 17:33 UTC, Chicanoss reviewed
Nice work, just check the validation pipe

2023-10-25 18:29 UTC, Chicanoss reviewed
Nice work

2023-10-26 11:52 UTC, Isioblast approved these changes

2023-10-26 12:06 UTC, kbarbry approved these changes

2023-10-26 12:09 UTC, merged