107 channel member resolverspec FULL
kbarbry/ft_transcendence pull request #118
Opened 2023-10-20 14:20 UTC by Isioblast

2023-10-24 16:35 UTC, Chicanoss approved these changes
Nice work

2023-10-24 16:47 UTC, kbarbry requested changes
Nickname is not mandatory in channel member, change it in dtos, resolver, andeverywhere necessary, even the database if it's not done yet

2023-10-24 16:47 UTC, kbarbry commented on backend/src/channel-member/channel-member.resolver.spec.ts
> +      it('nickname - too long', async () => {
nickname is not mandatory

2023-10-26 12:05 UTC, kbarbry approved these changes

2023-10-26 12:09 UTC, merged